import esbuild from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'src');
const DIST = join(ROOT, 'dist');

mkdirSync(DIST, { recursive: true });

const result = await esbuild.build({
  entryPoints: [join(SRC, 'Code.ts')],
  bundle: true,
  format: 'esm',
  target: 'es2020',
  platform: 'neutral',
  sourcemap: false,
  minify: false,
  treeShaking: true,
  write: false,
  logLevel: 'info',
});

if (!result.outputFiles || result.outputFiles.length === 0) {
  throw new Error('esbuild produced no output');
}

let bundled: string = result.outputFiles[0].text;

bundled = bundled.replace(/^export\s*\{[^}]*\};?\s*$/gm, '');
bundled = bundled.replace(/^export\s+(function|class|const|let|var|async\s+function)\b/gm, '$1');
bundled = bundled.replace(/^export\s+default\s+(function|class)\b/gm, '$1');
bundled = bundled.replace(/^export\s+default\s+.+$/gm, '');

const header = `/**
 * JobHelp Apps Script — single-file bundle
 *
 * Generated by extension-app/appsscript/scripts/build.mts.
 * Paste this entire file into the Apps Script Code.gs editor.
 *
 * Required Script Properties (Project Settings → Script Properties):
 *   ANTHROPIC_API_KEY — your Anthropic API key (sk-ant-...)
 *
 * Web app deployment:
 *   Deploy → New deployment → Type: Web app
 *   Execute as: Me · Who has access: Only myself (or Anyone with link)
 *   Copy the /exec URL into the extension Settings tab.
 */

`;

const footer = `

// Apps Script web-app entry point. ApiAction "doPost" is exported by Code.ts
// and was de-exported by the build script — it remains a top-level function
// here, which is what Apps Script requires.
`;

const finalCode = header + bundled.trim() + '\n' + footer;
const outPath = join(DIST, 'Code.gs');
writeFileSync(outPath, finalCode);

console.log(`Built ${outPath}`);
console.log(`Size: ${(finalCode.length / 1024).toFixed(1)} KB`);
console.log('Paste this file into the Apps Script editor as Code.gs.');
