/**
 * appsscript/scripts/build.mjs
 *
 * Bundles all TypeScript modules under appsscript/src/ into a single
 * `appsscript/dist/Code.gs` that you paste into the Apps Script editor.
 *
 * Why a custom build:
 *   - Google Apps Script's V8 runtime supports modern JS but does NOT allow
 *     ES module syntax (`import`/`export`). We bundle into one file and strip
 *     the export keyword post-hoc so all declarations end up at top level.
 *   - The Apps Script web-app entry point `doPost` must be a top-level function;
 *     this script ensures it is.
 *
 * Usage:
 *   node appsscript/scripts/build.mjs
 *
 * Output:
 *   appsscript/dist/Code.gs   (paste this into Apps Script)
 */

import esbuild from 'esbuild';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'src');
const DIST = join(ROOT, 'dist');

mkdirSync(DIST, { recursive: true });

// Build with esbuild in ESM format, then post-process to strip export syntax.
const result = await esbuild.build({
  entryPoints: [join(SRC, 'Code.ts')],
  bundle: true,
  format: 'esm',
  target: 'es2020',
  platform: 'neutral',
  // Apps Script doesn't allow source maps inline; keep build-time only
  sourcemap: false,
  minify: false,
  treeShaking: true,
  write: false,
  logLevel: 'info',
});

if (!result.outputFiles || result.outputFiles.length === 0) {
  throw new Error('esbuild produced no output');
}

let bundled = result.outputFiles[0].text;

// ─── Post-process to make valid Apps Script JS ───────────────────────────────
//
// 1. Remove `export { foo as bar, ... };` blocks (esbuild adds these at top level)
// 2. Strip `export ` prefix from declarations: `export function`, `export class`,
//    `export const`, `export let`, `export var`
// 3. Strip `export default` (replace with declaration without prefix)
// 4. Apps Script doesn't support `import.meta.url` either — replace with empty
//    string at this layer (none of our bundled code should reach this).

// Remove export {...} blocks (multi-line aware)
bundled = bundled.replace(/^export\s*\{[^}]*\};?\s*$/gm, '');
// Strip leading "export " on declarations
bundled = bundled.replace(/^export\s+(function|class|const|let|var|async\s+function)\b/gm, '$1');
// Strip "export default function ..." → "function ..."
bundled = bundled.replace(/^export\s+default\s+(function|class)\b/gm, '$1');
// Strip "export default <expr>;" → drop entirely (Apps Script has no concept of default exports)
bundled = bundled.replace(/^export\s+default\s+.+$/gm, '');

const header = `/**
 * JobHelp Apps Script — single-file bundle
 *
 * Generated by appsscript/scripts/build.mjs.
 * Paste this entire file into the Apps Script Code.gs editor.
 *
 * Required Script Properties (Project Settings → Script Properties):
 *   ANTHROPIC_API_KEY — your Anthropic API key (sk-ant-...)
 *
 * Web app deployment:
 *   Deploy → New deployment → Type: Web app
 *   Execute as: Me · Who has access: Only myself (or Anyone with link)
 *   Copy the /exec URL into the extension Settings tab.
 */

`;

const footer = `

// Apps Script web-app entry point. ApiAction "doPost" is exported by Code.ts
// and was de-exported by the build script — it remains a top-level function
// here, which is what Apps Script requires.
`;

const finalCode = header + bundled.trim() + '\n' + footer;
const outPath = join(DIST, 'Code.gs');
writeFileSync(outPath, finalCode);

console.log(`Built ${outPath}`);
console.log(`Size: ${(finalCode.length / 1024).toFixed(1)} KB`);
console.log('Paste this file into the Apps Script editor as Code.gs.');
